<?php
class UserSeeder extends Seeder 
{

    public function run()
    {

        $user = new User();
        $user->username = 'Logan';
        $user->first_name = 'Logan';
        $user->last_name = 'Farmer';
        $user->email = 'thevisagiftcard@gmail.com';
        $user->interests = 'PHP, MySQL, Python, Boo, LAMP+J, MySQL, Python, Ruby on Rails';
        $user->password = 'logan';
        $user->img_url = '/img/logan.jpg';
        $user->is_mentor = 1;
        $user->bio = 'A million dollars isnt cool. You know what is? A billion dollars.';
        $user->github_name = 'yungshark';
        $user->confirmed = 1;
        $user->save();
    
        $user1 = new User();
        $user1->username = 'PlatonicPoohBear';
        $user1->first_name = 'Nick';
        $user1->last_name = 'Vrzalik';
        $user1->email = 'nicholas.vrzalik@hotmail.com';
        $user1->interests = 'Boo, LAMP+J, C#, Boo, LAMP+J, MySQL, Python, Ruby on Rails';
        $user1->password = 'nick';
        $user1->img_url = '/img/nick.jpg';
        $user1->bio = 'A million dollars isnt cool. You know what is? A billion dollars.';
        $user1->github_name = 'PlatonicPoohBear';
        $user1->confirmed = 1;
        $user1->save();
    
        $user2 = new User();
        $user2->username = 'burneyburney';
        $user2->first_name = 'Burney';
        $user2->last_name = 'Burney';
        $user2->email = 'burney318@gmail.com';
        $user2->interests = 'PHP, JavaScript, C#, Boo';
        $user2->password = 'burney';
        $user2->img_url = '/img/burney.jpg';
        $user2->bio = 'A million dollars isnt cool. You know what is? A billion dollars.';
        $user2->github_name = 'burneyburney';
        $user2->confirmed = 1;
        $user2->save();
    
        $user3 = new User();
        $user3->username = 'Gregory-Bickham';
        $user3->first_name = 'Gregory';
        $user3->last_name = 'Bickham';
        $user3->email = 'gregory.bickham@gmail.com';
        $user3->interests = 'PHP, JavaScript, C#, Boo';
        $user3->password = 'greg';
        $user3->img_url = '/img/greg.jpg';
        $user3->bio = 'A million dollars isnt cool. You know what is? A billion dollars.';
        $user3->github_name = 'Gregory-Bickham';
        $user3->confirmed = 1;
        $user3->save();
    
        $user4 = new User();
        $user4->username = 'Penthious';
        $user4->first_name = 'Tomas';
        $user4->last_name = 'Leffew';
        $user4->email = 'tleffew1994@gmail.com';
        $user4->interests = 'C#, Boo, Cobol, .NET, Assembly';
        $user4->password = 'tomas';
        $user4->img_url = '/img/thomas.jpeg';
        $user4->bio = 'A million dollars isnt cool. You know what is? A billion dollars.';
        $user4->github_name = 'Penthious';
        $user4->confirmed = 1;
        $user4->save();

        $user5 = new User();
        $user5->username = 'Bobby';
        $user5->first_name = 'Bob';
        $user5->last_name = 'Bobberson';
        $user5->email = 'bob@gmail.com';
        $user5->interests = 'C#, Boo, Cobol, .NET, Assembly';
        $user5->password = 'bobberson';
        $user5->img_url = 'img/phpAu4hV4';
        $user5->is_mentor = 1;
        $user5->bio = 'A million dollars isnt cool. You know what is? A billion dollars.';
        $user5->github_name = 'Bobby';
        $user5->confirmed = 1;
        $user5->save();

        $user = new User();
        $user->username = 'jsullivan0';
        $user->first_name = 'Jimmy';
        $user->last_name = 'Sullivan';
        $user->email = 'jsullivan0@illinois.edu';
        $user->interests = 'MySQL, Python, LAMP+J';
        $user->password = 'logan';
        $user->img_url = 'img/1.jpg';
        $user->is_mentor = 1;
        $user->bio = 'A woman\'s face with nature\'s own hand painted';
        $user->github_name = 'jsullivan0';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'treid1';
        $user->first_name = 'Theresa';
        $user->last_name = 'Reid';
        $user->email = 'treid1@hibu.com';
        $user->interests = 'Boo, C#, Ruby';
        $user->password = 'logan';
        $user->img_url = '/img/2.jpg';
        $user->is_mentor = 1;
        $user->bio = 'Accuse me thus: that I have scanted all';
        $user->github_name = 'treid1';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'jwebb2';
        $user->first_name = 'Joseph';
        $user->last_name = 'Webb';
        $user->email = 'jwebb2@ifeng.com';
        $user->interests = 'PHP, Cobol, Ruby';
        $user->password = 'logan';
        $user->img_url = '/img/3.jpg';
        $user->is_mentor = 1;
        $user->bio = 'Against my love shall be as I am now';
        $user->github_name = 'jwebb2';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'rgarza3';
        $user->first_name = 'Russell';
        $user->last_name = 'Garza';
        $user->email = 'rgarza3@aol.com';
        $user->interests = 'MySQL, PHP, JavaScript';
        $user->password = 'logan';
        $user->img_url = '/img/4.jpg';
        $user->is_mentor = 1;
        $user->bio = 'Ah! wherefore with infection should he live';
        $user->github_name = 'rgarza3';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'jfernandez4';
        $user->first_name = 'Janet';
        $user->last_name = 'Fernandez';
        $user->email = 'jfernandez4@unicef.org';
        $user->interests = 'Ruby, C, JavaScript';
        $user->password = 'logan';
        $user->img_url = '/img/5.jpg';
        $user->is_mentor = 1;
        $user->bio = 'Alack! what poverty my Muse brings forth';
        $user->github_name = 'jfernandez4';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'rcampbell5';
        $user->first_name = 'Randy';
        $user->last_name = 'Campbell';
        $user->email = 'rcampbell5@unicef.org';
        $user->interests = 'Java, C#, JavaScript';
        $user->password = 'logan';
        $user->img_url = '/img/6.jpg';
        $user->is_mentor = 1;
        $user->bio = 'Against that time, if ever that time come';
        $user->github_name = 'rcampbell5';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'hgarcia6';
        $user->first_name = 'Howard';
        $user->last_name = 'Garcia';
        $user->email = 'hgarcia6@unicef.org';
        $user->interests = 'Boo, .NET, Ruby';
        $user->password = 'logan';
        $user->img_url = '/img/7.jpg';
        $user->is_mentor = 1;
        $user->bio = 'As a decrepit father takes delight';
        $user->github_name = 'hgarcia6';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'anelson7';
        $user->first_name = 'Arthur';
        $user->last_name = 'Nelson';
        $user->email = 'anelson7@unicef.org';
        $user->interests = 'C#, Smalltalk, Ruby';
        $user->password = 'logan';
        $user->img_url = '/img/8.jpg';
        $user->is_mentor = 1;
        $user->bio = 'Be wise as thou art cruel; do not press';
        $user->github_name = 'anelson7';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'jdavis8';
        $user->first_name = 'Jose';
        $user->last_name = 'Davis';
        $user->email = 'jdavis8@unicef.org';
        $user->interests = 'PHP, Cobol, MySQL';
        $user->password = 'logan';
        $user->img_url = '/img/9.jpg';
        $user->is_mentor = 1;
        $user->bio = 'Being your slave what should I do but tend';
        $user->github_name = 'jdavis8';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'kbryant9';
        $user->first_name = 'Karen';
        $user->last_name = 'Bryant';
        $user->email = 'kbryant9@unicef.org';
        $user->interests = 'Scheme, JavaScript, MySQL';
        $user->password = 'logan';
        $user->img_url = '/img/10.jpg';
        $user->is_mentor = 1;
        $user->bio = 'As fast as thou shalt wane, so fast thou grow\'st';
        $user->github_name = 'kbryant9';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'prossa';
        $user->first_name = 'Pamela';
        $user->last_name = 'Ross';
        $user->email = 'prossa@unicef.org';
        $user->interests = 'PHP, JavaScript, MySQL';
        $user->password = 'logan';
        $user->img_url = '/img/11.jpg';
        $user->is_mentor = 0;
        $user->bio = 'Betwixt mine eye and heart a league is took';
        $user->github_name = 'prossa';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'wkelleyb';
        $user->first_name = 'Willie';
        $user->last_name = 'Kelly';
        $user->email = 'wkelleyb@unicef.org';
        $user->interests = '.NET, C#, Boo';
        $user->password = 'logan';
        $user->img_url = '/img/12.jpg';
        $user->is_mentor = 0;
        $user->bio = 'But do thy worst to steal thyself away';
        $user->github_name = 'wkelleyb';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'jbryantc';
        $user->first_name = 'Jesse';
        $user->last_name = 'Bryant';
        $user->email = 'jbryantc@unicef.org';
        $user->interests = 'MySQL, PHP, JavaScript';
        $user->password = 'logan';
        $user->img_url = '/img/13.jpg';
        $user->is_mentor = 0;
        $user->bio = 'But wherefore do not you a mightier way';
        $user->github_name = 'jbryantc';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'ajenkinsd';
        $user->first_name = 'Amy';
        $user->last_name = 'Jenkins';
        $user->email = 'ajenkinsd@unicef.org';
        $user->interests = 'Assembly, C, Ruby';
        $user->password = 'logan';
        $user->img_url = '/img/14.jpg';
        $user->is_mentor = 0;
        $user->bio = 'Canst thou, O cruel! say I love thee not';
        $user->github_name = 'ajenkinsd';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'awhitee';
        $user->first_name = 'Aaron';
        $user->last_name = 'White';
        $user->email = 'awhitee@unicef.org';
        $user->interests = 'PHP, MySQL, CSS';
        $user->password = 'logan';
        $user->img_url = '/img/15.jpg';
        $user->is_mentor = 0;
        $user->bio = 'Cupid laid by his brand and fell asleep';
        $user->github_name = 'awhitee';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'bwebbf';
        $user->first_name = 'Bruce';
        $user->last_name = 'Webb';
        $user->email = 'bwebbf@unicef.org';
        $user->interests = 'CSS, JavaScript, PHP';
        $user->password = 'logan';
        $user->img_url = '/img/16.jpg';
        $user->is_mentor = 0;
        $user->bio = 'Devouring Time, blunt thou the lion\'s paws';
        $user->github_name = 'bwebbf';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'bharveyg';
        $user->first_name = 'Bobby';
        $user->last_name = 'Harvey';
        $user->email = 'bharveyg@unicef.org';
        $user->interests = 'CSS, JavaScript, PHP';
        $user->password = 'logan';
        $user->img_url = '/img/17.jpg';
        $user->is_mentor = 0;
        $user->bio = 'Farewell! thou art too dear for my possessing';
        $user->github_name = 'bharveyg';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'mharrish';
        $user->first_name = 'Matthew';
        $user->last_name = 'Harris';
        $user->email = 'mharrish@unicef.org';
        $user->interests = 'Boo, .NET, PHP';
        $user->password = 'logan';
        $user->img_url = '/img/18.jpg';
        $user->is_mentor = 0;
        $user->bio = 'For shame deny that thou bear\'st love to any';
        $user->github_name = 'mharrish';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'dperryi';
        $user->first_name = 'Donald';
        $user->last_name = 'Perry';
        $user->email = 'dperryi@unicef.org';
        $user->interests = 'Boo, .NET, PHP';
        $user->password = 'logan';
        $user->img_url = '/img/19.jpg';
        $user->is_mentor = 0;
        $user->bio = 'From fairest creatures we desire increase';
        $user->github_name = 'dperryi';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'rmendozaj';
        $user->first_name = 'Ronald';
        $user->last_name = 'Mendoza';
        $user->email = 'rmendozaj@unicef.org';
        $user->interests = 'PHP, Laravel, MySQL';
        $user->password = 'logan';
        $user->img_url = '/img/20.jpg';
        $user->is_mentor = 0;
        $user->bio = 'From you have I been absent in the spring';
        $user->github_name = 'rmendozaj';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'hkelleyk';
        $user->first_name = 'Heather';
        $user->last_name = 'Kelly';
        $user->email = 'hkelleyk@unicef.org';
        $user->interests = 'JavaScript, JQuery, Meteor';
        $user->password = 'logan';
        $user->img_url = '/img/21.jpg';
        $user->is_mentor = 0;
        $user->bio = 'Full many a glorious morning have I seen';
        $user->github_name = 'hkelleyk';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'skennedyl';
        $user->first_name = 'Scott';
        $user->last_name = 'Kennedy';
        $user->email = 'skennedyl@unicef.org';
        $user->interests = 'Boo, .NET, PHP';
        $user->password = 'logan';
        $user->img_url = '/img/22.jpg';
        $user->is_mentor = 0;
        $user->bio = 'How can I then return in happy plight';
        $user->github_name = 'skennedyl';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'jwatkinsm';
        $user->first_name = 'Julia';
        $user->last_name = 'Watkins';
        $user->email = 'jwatkinsm@unicef.org';
        $user->interests = 'PHP, Laravel, MySQL';
        $user->password = 'logan';
        $user->img_url = '/img/23.jpg';
        $user->is_mentor = 0;
        $user->bio = 'How can my muse want subject to invent';
        $user->github_name = 'jwatkinsm';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'llarsonn';
        $user->first_name = 'Lori';
        $user->last_name = 'Lawson';
        $user->email = 'llarsonn@unicef.org';
        $user->interests = 'JavaScript, JQuery, Meteor';
        $user->password = 'logan';
        $user->img_url = '/img/24.jpg';
        $user->is_mentor = 0;
        $user->bio = 'How careful was I when I took my way';
        $user->github_name = 'llarsonn';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'mrobinsono';
        $user->first_name = 'Maria';
        $user->last_name = 'Robinson';
        $user->email = 'mrobinsono@unicef.org';
        $user->interests = 'Boo, .NET, PHP';
        $user->password = 'logan';
        $user->img_url = '/img/25.jpg';
        $user->is_mentor = 0;
        $user->bio = 'How heavy do I journey on the way';
        $user->github_name = 'mrobinsono';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'sfernandezp';
        $user->first_name = 'Stephanie';
        $user->last_name = 'Fernandez';
        $user->email = 'sfernandezp@unicef.org';
        $user->interests = 'PHP, Laravel, MySQL';
        $user->password = 'logan';
        $user->img_url = '/img/26.jpg';
        $user->is_mentor = 0;
        $user->bio = 'How like a winter hath my absence been';
        $user->github_name = 'sfernandezp';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'kwoodq';
        $user->first_name = 'Katherine';
        $user->last_name = 'Wood';
        $user->email = 'kwoodq@unicef.org';
        $user->interests = 'JavaScript, JQuery, Meteor';
        $user->password = 'logan';
        $user->img_url = '/img/27.jpg';
        $user->is_mentor = 0;
        $user->bio = 'How oft when thou, my music, music play\'st';
        $user->github_name = 'kwoodq';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'jbutlerr';
        $user->first_name = 'Jack';
        $user->last_name = 'Butler';
        $user->email = 'jbutlerr@unicef.org';
        $user->interests = 'Boo, .NET, PHP';
        $user->password = 'logan';
        $user->img_url = '/img/28.jpg';
        $user->is_mentor = 0;
        $user->bio = 'How sweet and lovely dost thou make the shame';
        $user->github_name = 'jbutlerr';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'eshaws';
        $user->first_name = 'Ernest';
        $user->last_name = 'Shaw';
        $user->email = 'eshaws@unicef.org';
        $user->interests = 'PHP, Laravel, MySQL';
        $user->password = 'logan';
        $user->img_url = '/img/29.jpg';
        $user->is_mentor = 0;
        $user->bio = 'I grant thou wert not married to my Muse';
        $user->github_name = 'eshaws';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'randersont';
        $user->first_name = 'Rachel';
        $user->last_name = 'Anderson';
        $user->email = 'randersont@unicef.org';
        $user->interests = 'JavaScript, JQuery, Meteor';
        $user->password = 'logan';
        $user->img_url = '/img/30.jpg';
        $user->is_mentor = 0;
        $user->bio = 'I never saw that you did painting need';
        $user->github_name = 'randersont';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'pspenceru';
        $user->first_name = 'Peter';
        $user->last_name = 'Spencer';
        $user->email = 'pspenceru@unicef.org';
        $user->interests = 'Boo, .NET, PHP';
        $user->password = 'logan';
        $user->img_url = '/img/31.jpg';
        $user->is_mentor = 0;
        $user->bio = 'If my dear love were but the child of state';
        $user->github_name = 'pspenceru';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'pscottv';
        $user->first_name = 'Philip';
        $user->last_name = 'Scott';
        $user->email = 'pscottv@unicef.org';
        $user->interests = 'PHP, Laravel, MySQL';
        $user->password = 'logan';
        $user->img_url = '/img/32.jpg';
        $user->is_mentor = 0;
        $user->bio = 'If the dull substance of my flesh were thought';
        $user->github_name = 'pscottv';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'kbutlerw';
        $user->first_name = 'Kenneth';
        $user->last_name = 'Butler';
        $user->email = 'kbutlerw@unicef.org';
        $user->interests = 'JavaScript, JQuery, Meteor';
        $user->password = 'logan';
        $user->img_url = '/img/33.jpg';
        $user->is_mentor = 0;
        $user->bio = 'If there be nothing new, but that which is';
        $user->github_name = 'kbutlerw';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'sbaileyx';
        $user->first_name = 'Sarah';
        $user->last_name = 'Bailey';
        $user->email = 'sbaileyx@unicef.org';
        $user->interests = 'Boo, .NET, PHP';
        $user->password = 'logan';
        $user->img_url = '/img/34.jpg';
        $user->is_mentor = 0;
        $user->bio = 'If thou survive my well-contented day';
        $user->github_name = 'sbaileyx';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'dharrisony';
        $user->first_name = 'Dennis';
        $user->last_name = 'Harrison';
        $user->email = 'dharrisony@unicef.org';
        $user->interests = 'PHP, Laravel, MySQL';
        $user->password = 'logan';
        $user->img_url = '/img/35.jpg';
        $user->is_mentor = 0;
        $user->bio = 'If the dull substance of my flesh were thought';
        $user->github_name = 'dharrisony';
        $user->confirmed = 1;
        $user->save();

        $user = new User();
        $user->username = 'pshawz';
        $user->first_name = 'Pamela';
        $user->last_name = 'Shaw';
        $user->email = 'pshawz@unicef.org';
        $user->interests = 'JavaScript, JQuery, Meteor';
        $user->password = 'logan';
        $user->img_url = '/img/36.jpg';
        $user->is_mentor = 0;
        $user->bio = 'You live in this, and dwell in lovers\' eyes.';
        $user->github_name = 'pshawz';
        $user->confirmed = 1;
        $user->save();
    
    }
}